
view:
    path:     /view/{fst}
    defaults:
        _controller: MSIFournisseurBundle:Commande:view
    requirements:
        fst: \w+

edit:
    path:     /edit/{cmde}/{cmdeLigne}
    defaults:
        _controller: MSIFournisseurBundle:Commande:edit
    requirements:
        cmde: \w+
        cmdeLigne: \d+

load_csv:
    path:     /load
    defaults:
        _controller: MSIFournisseurBundle:Commande:load
